version: '3.9'

services:

  consul-server:
    image: consul:1.15.2
    container_name: consul-server
    restart: always
    volumes:
     - ./consul/server.json:/consul/config/server.json:ro
    networks:
      service-network:
        ipv4_address: 192.168.0.10
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -client=192.168.0.10"
    healthcheck:
      test: curl -v http://192.168.0.10:8500/v1/agent/checks || exit 1
      interval: 10s
      timeout: 1s
      retries: 12
      start_period: 20s

  consul-add-kv-data:
    image: consul:1.15.2
    container_name: consul-add-kv-data
    networks:
      - service-network
    depends_on:
      consul-server:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        export CONSUL_HTTP_ADDR=192.168.0.10:8500
        consul kv put app/config/all-hazelcast-instances "192.168.0.11:5701,192.168.0.12:5701,192.168.0.13:5701"
        consul kv put app/config/hazelcast/map/name "loggingServiceMap"
        consul kv put app/config/hazelcast/queue/name "facade2messagesQueue"

  facade-service:
    image: facade-service:1.0
    container_name: facade-service
    environment:
      - SERVICE_NAME=facade-service
      - SERVICE_ID=facade-service1
      - SERVICE_PORT=8001
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.101
    ports:
      - 8001:8001
    deploy:
      replicas: 1
    depends_on:
      consul-add-kv-data:
        condition: service_completed_successfully

  messages-service1:
    image: messages-service:1.0
    container_name: messages-service1
    hostname: messages-service1
    environment:
      - SERVICE_NAME=messages-service
      - SERVICE_ID=messages-service1
      - SERVICE_PORT=8003
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.113
    ports:
      - 8013:8003
    deploy:
      replicas: 1

  messages-service2:
    image: messages-service:1.0
    container_name: messages-service2
    hostname: messages-service2
    environment:
      - SERVICE_NAME=messages-service
      - SERVICE_ID=messages-service2
      - SERVICE_PORT=8003
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.123
    ports:
      - 8023:8003
    deploy:
      replicas: 1

  logging-service1:
    image: logging-service:1.0
    container_name: logging-service1
    environment:
      - SERVICE_NAME=logging-service
      - SERVICE_ID=logging-service1
      - SERVICE_PORT=8002
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.112
    ports:
      - 8012:8002
    deploy:
      replicas: 1

  logging-service2:
    image: logging-service:1.0
    container_name: logging-service2
    hostname: logging-service2
    environment:
      - SERVICE_NAME=logging-service
      - SERVICE_ID=logging-service2
      - SERVICE_PORT=8002
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.122
    ports:
      - 8022:8002
    deploy:
      replicas: 1

  logging-service3:
    image: logging-service:1.0
    container_name: logging-service3
    hostname: logging-service3
    environment:
      - SERVICE_NAME=logging-service
      - SERVICE_ID=logging-service3
      - SERVICE_PORT=8002
      - CONSUL_URL="http://192.168.0.10:8500"
    networks:
      service-network:
        ipv4_address: 192.168.0.132
    ports:
      - 8032:8002
    deploy:
      replicas: 1

  hazelcast1:
    image: hazelcast/hazelcast:5.2.3
    container_name: hazelcast1
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      service-network:
        ipv4_address: 192.168.0.11
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    ports:
      - 5701:5701
    deploy:
      replicas: 1

  hazelcast2:
    image: hazelcast/hazelcast:5.2.3
    container_name: hazelcast2
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      service-network:
        ipv4_address: 192.168.0.12
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    ports:
      - 5702:5701
    deploy:
      replicas: 1

  hazelcast3:
    image: hazelcast/hazelcast:5.2.3
    container_name: hazelcast3
    environment:
      - LOGGING_LEVEL=INFO
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      service-network:
        ipv4_address: 192.168.0.13
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/config_ext/hazelcast.yaml
    ports:
      - 5703:5701
    deploy:
      replicas: 1

  hazelcast-management-center:
    image: hazelcast/management-center:5.2.1
    container_name: hazelcast-management-center
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3
    networks:
      service-network:
        ipv4_address: 192.168.0.14
    ports:
      - 8080:8080
    deploy:
      replicas: 1

networks:
  service-network:
    name: service-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
